/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuildRouteImport } from './routes/build'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildKeysRouteImport } from './routes/build/keys'
import { Route as BuildGamesRouteImport } from './routes/build/games'
import { Route as BuildDocsRouteImport } from './routes/build/docs'
import { Route as BuildAnalyticsRouteImport } from './routes/build/analytics'
import { Route as AppStakeRouteImport } from './routes/app/stake'
import { Route as AppPlayRouteImport } from './routes/app/play'
import { Route as AppFaucetRouteImport } from './routes/app/faucet'
import { Route as AppPlayIndexRouteImport } from './routes/app/play.index'
import { Route as BuildGamesNewRouteImport } from './routes/build/games.new'
import { Route as BuildGamesIdRouteImport } from './routes/build/games.$id'
import { Route as AppPlaySlugRouteImport } from './routes/app/play.$slug'

const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildKeysRoute = BuildKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => BuildRoute,
} as any)
const BuildGamesRoute = BuildGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => BuildRoute,
} as any)
const BuildDocsRoute = BuildDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => BuildRoute,
} as any)
const BuildAnalyticsRoute = BuildAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BuildRoute,
} as any)
const AppStakeRoute = AppStakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppFaucetRoute = AppFaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayIndexRoute = AppPlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlayRoute,
} as any)
const BuildGamesNewRoute = BuildGamesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BuildGamesRoute,
} as any)
const BuildGamesIdRoute = BuildGamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuildGamesRoute,
} as any)
const AppPlaySlugRoute = AppPlaySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppPlayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/build': typeof BuildRouteWithChildren
  '/app/faucet': typeof AppFaucetRoute
  '/app/play': typeof AppPlayRouteWithChildren
  '/app/stake': typeof AppStakeRoute
  '/build/analytics': typeof BuildAnalyticsRoute
  '/build/docs': typeof BuildDocsRoute
  '/build/games': typeof BuildGamesRouteWithChildren
  '/build/keys': typeof BuildKeysRoute
  '/app/play/$slug': typeof AppPlaySlugRoute
  '/build/games/$id': typeof BuildGamesIdRoute
  '/build/games/new': typeof BuildGamesNewRoute
  '/app/play/': typeof AppPlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/build': typeof BuildRouteWithChildren
  '/app/faucet': typeof AppFaucetRoute
  '/app/stake': typeof AppStakeRoute
  '/build/analytics': typeof BuildAnalyticsRoute
  '/build/docs': typeof BuildDocsRoute
  '/build/games': typeof BuildGamesRouteWithChildren
  '/build/keys': typeof BuildKeysRoute
  '/app/play/$slug': typeof AppPlaySlugRoute
  '/build/games/$id': typeof BuildGamesIdRoute
  '/build/games/new': typeof BuildGamesNewRoute
  '/app/play': typeof AppPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/build': typeof BuildRouteWithChildren
  '/app/faucet': typeof AppFaucetRoute
  '/app/play': typeof AppPlayRouteWithChildren
  '/app/stake': typeof AppStakeRoute
  '/build/analytics': typeof BuildAnalyticsRoute
  '/build/docs': typeof BuildDocsRoute
  '/build/games': typeof BuildGamesRouteWithChildren
  '/build/keys': typeof BuildKeysRoute
  '/app/play/$slug': typeof AppPlaySlugRoute
  '/build/games/$id': typeof BuildGamesIdRoute
  '/build/games/new': typeof BuildGamesNewRoute
  '/app/play/': typeof AppPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/build'
    | '/app/faucet'
    | '/app/play'
    | '/app/stake'
    | '/build/analytics'
    | '/build/docs'
    | '/build/games'
    | '/build/keys'
    | '/app/play/$slug'
    | '/build/games/$id'
    | '/build/games/new'
    | '/app/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/build'
    | '/app/faucet'
    | '/app/stake'
    | '/build/analytics'
    | '/build/docs'
    | '/build/games'
    | '/build/keys'
    | '/app/play/$slug'
    | '/build/games/$id'
    | '/build/games/new'
    | '/app/play'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/build'
    | '/app/faucet'
    | '/app/play'
    | '/app/stake'
    | '/build/analytics'
    | '/build/docs'
    | '/build/games'
    | '/build/keys'
    | '/app/play/$slug'
    | '/build/games/$id'
    | '/build/games/new'
    | '/app/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BuildRoute: typeof BuildRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/keys': {
      id: '/build/keys'
      path: '/keys'
      fullPath: '/build/keys'
      preLoaderRoute: typeof BuildKeysRouteImport
      parentRoute: typeof BuildRoute
    }
    '/build/games': {
      id: '/build/games'
      path: '/games'
      fullPath: '/build/games'
      preLoaderRoute: typeof BuildGamesRouteImport
      parentRoute: typeof BuildRoute
    }
    '/build/docs': {
      id: '/build/docs'
      path: '/docs'
      fullPath: '/build/docs'
      preLoaderRoute: typeof BuildDocsRouteImport
      parentRoute: typeof BuildRoute
    }
    '/build/analytics': {
      id: '/build/analytics'
      path: '/analytics'
      fullPath: '/build/analytics'
      preLoaderRoute: typeof BuildAnalyticsRouteImport
      parentRoute: typeof BuildRoute
    }
    '/app/stake': {
      id: '/app/stake'
      path: '/stake'
      fullPath: '/app/stake'
      preLoaderRoute: typeof AppStakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play': {
      id: '/app/play'
      path: '/play'
      fullPath: '/app/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faucet': {
      id: '/app/faucet'
      path: '/faucet'
      fullPath: '/app/faucet'
      preLoaderRoute: typeof AppFaucetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play/': {
      id: '/app/play/'
      path: '/'
      fullPath: '/app/play/'
      preLoaderRoute: typeof AppPlayIndexRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/build/games/new': {
      id: '/build/games/new'
      path: '/new'
      fullPath: '/build/games/new'
      preLoaderRoute: typeof BuildGamesNewRouteImport
      parentRoute: typeof BuildGamesRoute
    }
    '/build/games/$id': {
      id: '/build/games/$id'
      path: '/$id'
      fullPath: '/build/games/$id'
      preLoaderRoute: typeof BuildGamesIdRouteImport
      parentRoute: typeof BuildGamesRoute
    }
    '/app/play/$slug': {
      id: '/app/play/$slug'
      path: '/$slug'
      fullPath: '/app/play/$slug'
      preLoaderRoute: typeof AppPlaySlugRouteImport
      parentRoute: typeof AppPlayRoute
    }
  }
}

interface AppPlayRouteChildren {
  AppPlaySlugRoute: typeof AppPlaySlugRoute
  AppPlayIndexRoute: typeof AppPlayIndexRoute
}

const AppPlayRouteChildren: AppPlayRouteChildren = {
  AppPlaySlugRoute: AppPlaySlugRoute,
  AppPlayIndexRoute: AppPlayIndexRoute,
}

const AppPlayRouteWithChildren =
  AppPlayRoute._addFileChildren(AppPlayRouteChildren)

interface AppRouteChildren {
  AppFaucetRoute: typeof AppFaucetRoute
  AppPlayRoute: typeof AppPlayRouteWithChildren
  AppStakeRoute: typeof AppStakeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFaucetRoute: AppFaucetRoute,
  AppPlayRoute: AppPlayRouteWithChildren,
  AppStakeRoute: AppStakeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BuildGamesRouteChildren {
  BuildGamesIdRoute: typeof BuildGamesIdRoute
  BuildGamesNewRoute: typeof BuildGamesNewRoute
}

const BuildGamesRouteChildren: BuildGamesRouteChildren = {
  BuildGamesIdRoute: BuildGamesIdRoute,
  BuildGamesNewRoute: BuildGamesNewRoute,
}

const BuildGamesRouteWithChildren = BuildGamesRoute._addFileChildren(
  BuildGamesRouteChildren,
)

interface BuildRouteChildren {
  BuildAnalyticsRoute: typeof BuildAnalyticsRoute
  BuildDocsRoute: typeof BuildDocsRoute
  BuildGamesRoute: typeof BuildGamesRouteWithChildren
  BuildKeysRoute: typeof BuildKeysRoute
}

const BuildRouteChildren: BuildRouteChildren = {
  BuildAnalyticsRoute: BuildAnalyticsRoute,
  BuildDocsRoute: BuildDocsRoute,
  BuildGamesRoute: BuildGamesRouteWithChildren,
  BuildKeysRoute: BuildKeysRoute,
}

const BuildRouteWithChildren = BuildRoute._addFileChildren(BuildRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BuildRoute: BuildRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
