/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuildRouteImport } from './routes/build'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStakeRouteImport } from './routes/app/stake'
import { Route as AppPlayRouteImport } from './routes/app/play'
import { Route as AppPlayIndexRouteImport } from './routes/app/play.index'
import { Route as AppPlaySlugRouteImport } from './routes/app/play.$slug'

const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStakeRoute = AppStakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayIndexRoute = AppPlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlaySlugRoute = AppPlaySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppPlayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/build': typeof BuildRoute
  '/app/play': typeof AppPlayRouteWithChildren
  '/app/stake': typeof AppStakeRoute
  '/app/play/$slug': typeof AppPlaySlugRoute
  '/app/play/': typeof AppPlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/build': typeof BuildRoute
  '/app/stake': typeof AppStakeRoute
  '/app/play/$slug': typeof AppPlaySlugRoute
  '/app/play': typeof AppPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/build': typeof BuildRoute
  '/app/play': typeof AppPlayRouteWithChildren
  '/app/stake': typeof AppStakeRoute
  '/app/play/$slug': typeof AppPlaySlugRoute
  '/app/play/': typeof AppPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/build'
    | '/app/play'
    | '/app/stake'
    | '/app/play/$slug'
    | '/app/play/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/build' | '/app/stake' | '/app/play/$slug' | '/app/play'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/build'
    | '/app/play'
    | '/app/stake'
    | '/app/play/$slug'
    | '/app/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BuildRoute: typeof BuildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stake': {
      id: '/app/stake'
      path: '/stake'
      fullPath: '/app/stake'
      preLoaderRoute: typeof AppStakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play': {
      id: '/app/play'
      path: '/play'
      fullPath: '/app/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play/': {
      id: '/app/play/'
      path: '/'
      fullPath: '/app/play/'
      preLoaderRoute: typeof AppPlayIndexRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/app/play/$slug': {
      id: '/app/play/$slug'
      path: '/$slug'
      fullPath: '/app/play/$slug'
      preLoaderRoute: typeof AppPlaySlugRouteImport
      parentRoute: typeof AppPlayRoute
    }
  }
}

interface AppPlayRouteChildren {
  AppPlaySlugRoute: typeof AppPlaySlugRoute
  AppPlayIndexRoute: typeof AppPlayIndexRoute
}

const AppPlayRouteChildren: AppPlayRouteChildren = {
  AppPlaySlugRoute: AppPlaySlugRoute,
  AppPlayIndexRoute: AppPlayIndexRoute,
}

const AppPlayRouteWithChildren =
  AppPlayRoute._addFileChildren(AppPlayRouteChildren)

interface AppRouteChildren {
  AppPlayRoute: typeof AppPlayRouteWithChildren
  AppStakeRoute: typeof AppStakeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPlayRoute: AppPlayRouteWithChildren,
  AppStakeRoute: AppStakeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BuildRoute: BuildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
